### ISSUE TITLE
nonempty git diff after coq ci build

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat#106]
```
?? compatibility/Coq__8_20__Compat.v
in _build_ci/fiat_parsers/etc/coq-scripts
```

**Comment by JasonGross** [comment]
Yes, this is the hack I added in https://github.com/JasonGross/coq-scripts/commit/53b45389ba8c95b6fd25387ec781f0d46cec10e1 so that instead of needing to manually update coq-scripts on every Coq version bump, it'll just automatically create symlinks to the last known version.  Is this a big problem?

**Comment by andres-erbsen** [comment]
could you also .gitignore these modifications? I'm using git diff to detect which ci developments I need to send overlays to

**Comment by JasonGross** [comment]
Done
