### ISSUE TITLE
[coq] Please update the repository for Coq 8.12

### ISSUE THREAD

**Issue by ejgallego** [mit-plv/fiat#30]
c.f. https://github.com/coq/coq/pull/11158 

I tried to do it but found some problems.

On the long term it'd be great if we could avoid manual action, for example Compcert does work with unknown Coq versions but emits a warning.

**Comment by JasonGross** [comment]
Should hopefully be fixed by f679b8bc361b1756489bde1ce4a4cfffd33a440f, and in 7a17fa7c034418f84880343b4518e350f9b6b1c6 I've changed the warning into an error.  Feel free to re-open if this does not work.
